spring.application.name=incident-triage-service

# PostgreSQL connection -- same DB as Python service
spring.datasource.url=jdbc:postgresql://localhost:5432/triage_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:pratham123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8080